version: '3.1'
services:
  API:
    image: 'sonny-wecan-assignment'
    ports:
      - "8000:8000"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:postgresql://PostgreSQL:5432/voucher-db
      - spring.datasource.username=postgres
      - spring.datasource.password=admin
      - spring.jpa.hibernate.ddl-auto=validate

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=voucher-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
