server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voucher-db?serverTimezone=UTC
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    openInView: true
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      format_sql: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.proc.param_null_passing: true
logging:
  level:
    liquibase: INFO
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
  file:
    path: /tmp/log/wecan-assignment
